FROM nginx:stable
RUN apt-get update \
    && apt-get install -y vim \
    && apt-get install -y net-tools \
    && apt-get install -y wget \
    && apt-get install -y procps \
    && apt-get install -y curl
